build:
	g++ -std=c++11 -pthread -Wall -pedantic -g server.cpp -o server

# No run target because this Makefile only compiles the server
# Server should be run in other tests with nodes

clean:
	rm -f server
